language: c
compiler:
  - gcc
  - clang
script:
  - ./autogen.sh
  - ./configure
  - make -j
  - sudo make install
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y libnss3-dev libsctp-dev
